# Generated by Django 5.1.2 on 2024-12-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bookInstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bookinstance'),
        ),
    ]
